url: http://clubcedille.github.io/

# Site settings
title: Club Cedille
email: clubcedille@gmail.com
description: "Club Cedille Description"
image: "//avatars3.githubusercontent.com/u/6483038"

# Resource types
collections:
  # - posts
  - projects

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fec503
  secondary: ee9911
  secondary-dark: '000'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/clubcedille
  - title: github
    url: http://github.com/ClubCedille

# Postal address (add as many lines as necessary)
address:
  - line: Cedille
  - line: 1100, rue Notre-Dame Ouest
  - line: Montréal (Québec) H3C 1K3
  - line: Local A-1726
  
defaults:
  -
    scope: 
      path: "" # All files
    values:
      lang: fr

# Build settings
markdown: kramdown
permalink: pretty
